# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Api-Examples-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'QNRTCKit-iOS', :path =>'../QNRTCKit-iOS.podspec'

  pod 'Masonry', '1.1.0'

  # Pods for Api-Examples-iOS

end
