#!/bin/bash
#假设 pili-webrtc-m75 和 pili-rtc-ios-kit 处于同一目录下
cp ../../../../../pili-webrtc-m75/out_ios_libs/librtc_sdk_objc.a  .

cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCCodecSpecificInfo.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCEncodedImage.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCI420Buffer.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCLogging.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCMacros.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCMutableI420Buffer.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCMutableYUVPlanarBuffer.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCRtpFragmentationHeader.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCVideoCapturer.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCVideoCodecInfo.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCVideoDecoder.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCVideoDecoderFactory.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCVideoEncoder.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCVideoEncoderFactory.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCVideoEncoderQpThresholds.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCVideoEncoderSettings.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCVideoFrame.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCVideoFrameBuffer.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCVideoRenderer.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/base/RTCYUVPlanarBuffer.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/audio/RTCAudioSession.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/audio/QNRTCAudioDeviceAdapter.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/audio/QNRTCAudioRemoteOutputAdapter.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/audio/RTCAudioSessionConfiguration.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/capturer/QNRTCVideoCapturerAdapter.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/capturer/RTCFileVideoCapturer.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/renderer/metal/RTCMTLVideoView.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/renderer/opengl/RTCEAGLVideoView.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/renderer/opengl/RTCVideoViewShading.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/video_codec/RTCCodecSpecificInfoH264.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/video_codec/RTCDefaultVideoDecoderFactory.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/video_codec/RTCDefaultVideoEncoderFactory.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/video_codec/RTCH264ProfileLevelId.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/video_codec/RTCVideoDecoderFactoryH264.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/video_codec/RTCVideoDecoderH264.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/video_codec/RTCVideoEncoderFactoryH264.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/video_codec/RTCVideoEncoderH264.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/components/video_frame_buffer/RTCCVPixelBuffer.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/helpers/RTCCameraPreviewView.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/helpers/RTCDispatcher.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/helpers/UIDevice+RTCDevice.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCAudioSource.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCAudioTrack.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCConfiguration.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCDataChannel.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCDataChannelConfiguration.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCFieldTrials.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCIceCandidate.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCIceServer.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCIntervalRange.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCLegacyStatsReport.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCMediaConstraints.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCMediaSource.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCMediaStream.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCMediaStreamTrack.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCMetrics.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCMetricsSampleInfo.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCPeerConnection.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCPeerConnectionFactory.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCPeerConnectionFactoryOptions.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCRtcpParameters.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCRtpCodecParameters.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCRtpEncodingParameters.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCRtpHeaderExtension.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCRtpParameters.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCRtpReceiver.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCRtpSender.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/QNFrameDecryptor.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/QNFrameEncryptor.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCRtpTransceiver.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCDtmfSender.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCSSLAdapter.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCSessionDescription.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCTracing.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCCertificate.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCCryptoOptions.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCVideoSource.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCVideoTrack.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/video_codec/RTCVideoCodecConstants.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/video_codec/RTCVideoDecoderVP8.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/video_codec/RTCVideoDecoderVP9.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/video_codec/RTCVideoEncoderVP8.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/video_codec/RTCVideoEncoderVP9.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/video_frame_buffer/RTCNativeI420Buffer.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/video_frame_buffer/RTCNativeMutableI420Buffer.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCFileLogger.h .
cp ../../../../../pili-webrtc-m75/sdk/objc/api/peerconnection/RTCStatisticsReport.h  .

